[project]
name = "xpos"
authors = [
    { name = "Ali Raza", email = "ar.frappe.dev@gmail.com"}
]
description = "A modern, offline-capable Point of Sale application for Frappe and ERPNext"
requires-python = ">=3.10"
readme = "README.md"
license = { text = "MIT" }
dynamic = ["version"]
keywords = ["frappe", "erpnext", "xpos", "point-of-sale", "retail", "offline", "electron", "pwa"]

dependencies = [
    # "frappe~=15.0.0" # Installed and managed by bench.
    "python-barcode>=0.16.1",
    "qrcode[pil]>=8.2",
]

[project.urls]
Homepage = "https://github.com/kodlyft/xpos"
Repository = "https://github.com/kodlyft/xpos"
Issues = "https://github.com/kodlyft/xpos/issues"
Changelog = "https://github.com/kodlyft/xpos/releases"

[build-system]
requires = ["flit_core >=4.1.0,<5"]
build-backend = "flit_core.buildapi"

# These dependencies are only installed when developer mode is enabled
[tool.bench.dev-dependencies]
# package_name = "~=1.1.0"

[tool.bench.frappe-dependencies]
frappe = ">=16.0.0,<17.0.0"

[tool.ruff]
line-length = 110
target-version = "py310"

[tool.ruff.lint]
typing-modules = ["frappe.types.DF"]

[tool.ruff.format]
quote-style = "double"
indent-style = "tab"
docstring-code-format = true
